# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fd33a1808c7017c9db6d58035e01aa5c8378c86a9f700b186a3ce169e10b05709989dc450042cc2dec8337931acc48d9ad693c52e1c49d58cdf98d7979f3cb7a

test:
  secret_key_base: 43e6a96965f39cd5e045fb64d4a9b8cdfc008a7cc6eb82f6bc160f5dffe1d02d38f10878f5fb998feee56433efa3aabc59cd599cf50feadf9e16793f07cafe31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
